version: "3"

services:
  database:
    image: postgres:17
    container_name: betheros-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: betheros
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./data/pg:/data/postgres

  app:
    build: .
    container_name: betheros-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database

  stripe-cli:
    image: stripe/stripe-cli:latest
    command: listen --api-key ${STRIPE_SECRET_KEY} --forward-to http://app:3000/stripe/webhook
    env_file:
      - .env
    depends_on:
      - app