name: AI Code Review

on:
  pull_request:
    types: [labeled]

jobs:
  review:
    if: |
      github.event.label.name == 'ia-reviewer'

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - uses: Renan1fps/ai-code-reviewer@v1
        with:
          llm_provider:  ${{ vars.LLM_PROVIDER || 'anthropic' }}
          pr_number: ${{ github.event.issue.number }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          style_guide_path: './docs/style-guide.md'
          skills_path: './docs/skills'